name: Check Changelog for Database Changes

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in init_db
        id: check_init_db
        run: |
          git fetch origin ${{ github.base_ref }}:base_branch
          DIFF_FILES=$(git diff --name-only base_branch -- init_db/)
          echo "diff_files=$DIFF_FILES" >> $GITHUB_ENV
          if [ -z "$DIFF_FILES" ]; then
            echo "No changes detected in init_db."
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected in init_db: $DIFF_FILES"
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Post comment on PR
        if: env.changes == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ Changes detected in \`init_db\`, but no new changelog files found in \`src/main/resources/db/changelog\`. Please add the necessary changelog files."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
